services:
  html_to_pdf_printer_client_app_legacy:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: html_to_pdf_printer_client_app_legacy
    volumes:
      - .:/app
      - ./vendor:/app/vendor
      - ./composer.lock:/app/composer.lock
    working_dir: /app
    tty: true
    command: |
      sh -c "
      composer install --no-dev \
      && bash" 

  html_to_pdf_printer_client_test_legacy:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: html_to_pdf_printer_client_test_legacy
    volumes:
      - .:/app
      - ./test_vendor:/app/vendor
      - ./composer.test.lock:/app/composer.lock
    working_dir: /app
    command: |
      sh -c "
      composer install && \
      vendor/bin/phpunit test/"
    depends_on:
      - html_to_pdf_printer_client_app_legacy
